name: Bump version when tests are updated

on:
  push:
    branches:
      - main
    paths:
      - src-tauri/resources/**

jobs:
  bump-version:
    name: "Bump Version on master"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Get the current Version
        id: getCurrentVersion
        run: |
          TAG="v$(cat package.json | grep '"version"' | cut -d ':' -f 2 | sed 's/"//g' | sed 's/\s\+//g')"
          echo "tag=${TAG}" >> "$GITHUB_OUTPUT"

      - name: Bump the version
        id: bumpVersion
        run: |
          NEW_TAG=$(echo ${{ steps.getCurrentVersion.outputs.tag }} | awk -F. -v OFS=. '{$NF=$NF+1; print}')
          echo "new_tag=${NEW_TAG}" >> "$GITHUB_OUTPUT"
          
      - name: Print old and new tag
        run: |
          echo "Old tag: ${{ steps.getCurrentVersion.outputs.tag }}"
          echo "New tag: ${{ steps.bumpVersion.outputs.new_tag }}"

      - name: Modify README.md
        run: |
          # Update the version in the file
          sed -i "s/\"version\": \"$current_version\"/\"version\": \"$new_version\"/" package.json

          # Commit and push changes
          git config user.name "JorenSynaeveTM"
          git config user.email "joren.synaeve@thomasmore.be"
          git commit -am "Bump version to $new_version [skip ci]"
          git push