name: Bump version when tests are updated

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - src-tauri/resources/**

jobs:
  bump-version:
    name: "Bump Version on master"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Get the current Version
        id: getCurrentVersion
        run: |
          TAG="v$(cat package.json | grep '"version"' | cut -d ':' -f 2 | tr -d '"' | tr -d '[:space:]' | tr -d ',')"
          echo "tag=${TAG}" >> "$GITHUB_OUTPUT"

      - name: Bump the version
        id: bumpVersion
        run: |
          NEW_TAG=$(echo ${{ steps.getCurrentVersion.outputs.tag }} | awk -F. -v OFS=. '{$NF=$NF+1; print}')
          echo "new_tag=${NEW_TAG}" >> "$GITHUB_OUTPUT"
          
      - name: Print old and new tag
        run: |
          echo "Old tag: ${{ steps.getCurrentVersion.outputs.tag }}"
          echo "New tag: ${{ steps.bumpVersion.outputs.new_tag }}"

      - name: Modify README.md
        run: |
          # Update the version in the package.json file
          sed -i -e "s/\"version\": \".*\"/\"version\": \"${{ steps.bumpVersion.outputs.new_tag }}\"/" package.json

          # Make sure there is a newline at the end of the file
          sed -i -e '$a\' package.json

          # Echo the contents of the package.json file
          cat package.json

          # Commit and push changes
          echo "Config"
          git config user.name "JorenSynaeveTM"
          git config user.email "joren.synaeve@thomasmore.be"
          echo "Add"
          git add .
          echo "Commit"
          git commit -m "Bump version to ${{ steps.bumpVersion.outputs.new_tag }}"
          echo "Push"
          git push
          echo "Done"